# Arreglos en Python
## Librerías (o módulos) de Python

¿Qué es un vector? Es un elemento de un conjunto (e.g. $\mathbb{R}^n$)

Un elemento de $\mathbb{R}^n$ forma una **tupla** (en Python también existen las tuplas)

$$x=(x_1,x_2,\dots,x_n)$$

en donde cada $x_i$ es un número real.

In [1]:
# Una tupla
("a", "b")

('a', 'b')

In [2]:
x = (1,2)

y = (3,4)

x+y

(1, 2, 3, 4)

Sean $x,y\in \mathbb{R}^n$ dos vectores

$$x=(x_1,x_2,\dots,x_n+y_n)$$

y vamos a definir la multiplicación por escalar como sigue: sea $\alpha\in\mathbb{R}$

$$\alpha x=(\alpha x_1,\alpha x_2,\dots,\alpha x_n)$$

In [3]:
3*x

(1, 2, 1, 2, 1, 2)

Vamos a **definir** la operación vectorial a través de listas:

In [4]:
def m(x,y):
    z = x*y
    return z

In [5]:
m(2,3)

6

In [6]:
# Consideremos las siguientes dos listas

L_1 = [2,3,5,6,0]
L_2 = [6,3,1,0,2]

L_1 + L_2

[2, 3, 5, 6, 0, 6, 3, 1, 0, 2]

In [7]:
L_3 = [L_1[i]+L_2[i] for i in range(0,len(L_1))]
L_3

[8, 6, 6, 6, 2]

In [8]:
L_4 = [2*L_1[i] for i in range(len(L_1))]
L_4

[4, 6, 10, 12, 0]

In [9]:
def sumar_vectores(L,M):
    for i in range(len(L)):
        z = L[i]+M[i]
        return z

### Módulo [Numpy](https://numpy.org/)

In [10]:
import numpy as np

In [12]:
# Estamos convirtiendo una lista a un arreglo (es decir, un vector)

A_1 = np.array(L_1)

A_2 = np.array(L_2)

A_1 + A_2

array([8, 6, 6, 6, 2])

In [14]:
A_3 = np.array([4,12.1])

In [16]:
3*A_1

array([ 6,  9, 15, 18,  0])

In [17]:
A_1.cumsum()

array([ 2,  5, 10, 16, 16])

In [18]:
sum(A_1)

16

In [19]:
A_1.ndim # .ndim nos da la dimensióndel vector como objeto en Python

1

In [20]:
A_1.shape

(5,)

In [21]:
A_1.real

array([2, 3, 5, 6, 0])

### Matrices reales.

In [22]:
M = np.array([[1,2,3],[3,4,5]])
print(M)

[[1 2 3]
 [3 4 5]]


In [23]:
M.shape

(2, 3)

In [24]:
N = np.array([[4,0,1],[1,3,6]])
N

array([[4, 0, 1],
       [1, 3, 6]])

In [25]:
M + N # Siempre se pueden sumar matrices del mismo tamaño

array([[ 5,  2,  4],
       [ 4,  7, 11]])

In [26]:
2*M

array([[ 2,  4,  6],
       [ 6,  8, 10]])

### Accesos a elementos de arreglos

In [29]:
A_1

array([2, 3, 5, 6, 0])

In [30]:
A_1[2:4]

array([5, 6])

In [31]:
A_1[3:]

array([6, 0])

In [32]:
A_1[:4]

array([2, 3, 5, 6])

In [33]:
M

array([[1, 2, 3],
       [3, 4, 5]])

In [34]:
M[0][0]

1

In [36]:
M[0,0]

1

In [35]:
M[1][1]

4

### Slices

In [37]:
M[:,1:3]

array([[2, 3],
       [4, 5]])

In [38]:
M

array([[1, 2, 3],
       [3, 4, 5]])

In [41]:
N.T

array([[4, 1],
       [0, 3],
       [1, 6]])

In [42]:
Matriz = M @ N.T # Multiplicación de matrices

In [43]:
np.linalg.det(Matriz)

-110.00000000000004